### PR TITLE
Add MIT license headers

### PR DESCRIPTION
**Pull request by maxekman**
I also added a CONTRIBUTORS file.

### CODE REVIEW

**Comment by jcelliott** [comment]
Having the entire license in each file seems very redundant. My understanding is that you only need to have the license included in the project root and it applies to all the source in the project. Maybe we could omit the headers?

**Comment by maxekman** [comment]
From an aesthetics point of view I agree with you, but it's common practice to add the license header to every source file, as in the example here https://github.com/LeaVerou/cubic-bezier/pull/4. My thinking is that even a stray source file should be protected, in case anything would happen. I always do this for my open source projects.

**Comment by jcelliott** [comment]
But there are projects that do the opposite. For example [jquery](https://github.com/jquery/jquery/tree/master/src) doesn't even mention their (MIT) license in any of the source except [this file](https://github.com/jquery/jquery/blob/master/src/intro.js).

What about a compromise that just says what the license is in each file, something like this:

```
// Copyright (c) 2013 Joshua Elliott and contributors
// Released under the MIT License
// http://opensource.org/licenses/MIT
```

**Comment by maxekman** [comment]
Sure, that seems like a good solution! I'll commit changes. Copyright should be on only you, with contributors in a specific file though.

**Comment by maxekman** [comment]
Ok, ready to merge.

**Pull request merged**
