### PR TITLE
Begin work on adding RPC support:

### PR DESCRIPTION
**Pull request by josephschorr**
- Add the Call method for invoking a remote RPC
- Have the HELLO message include the roles
- Add a WaitForSession method which waits for the session WELCOME message. Callers can use this to make sure a valid session exists before starting RPC calls.

### CODE REVIEW

**Comment by jcelliott** [comment]
Thanks! Are you planning on adding any more commits to this PR, or should I merge it in?

**Comment by josephschorr** [comment]
I was planning on doing it in stages. If you think this PR is okay, please merge and then I'll start on the next one. My next PR should cover the REGISTER verb, with the following having UNREGISTER.

Also: Should I be writing tests for these changes and, if so, is there a preferred way to do so? I was unsure so I didn't in this PR.

**Comment by jcelliott** [comment]
> Also: Should I be writing tests for these changes and, if so, is there a preferred way to do so? I was unsure so I didn't in this PR.

Glad you asked. A lot of the initial work on v2 was done without thorough testing, just so we could get something working quickly. But I would like to be more consistent with testing at this point. I've started using [GoConvey](http://goconvey.co/) for testing and it's actually quite pleasant to use. See [my recent commit](https://github.com/jcelliott/turnpike/commit/66e8638f478e7183c6a7525f6b343559aaf7e899) adding authentication support for an example (specifically in `realm_test.go`). GoConvey works seamlessly with standard Go tests though, so using it isn't a requirement.

**Comment by josephschorr** [comment]
Sounds good. I'll try to emulate your testing style going forward.

**Comment by josephschorr** [comment]
Anything I should add/change before this is merged?

**Pull request merged**
