### PR TITLE
Add the ability to register and receive invocations of local RPC methods

### PR DESCRIPTION
**Pull request by josephschorr**
Note: This CL does not yet have testing.

### CODE REVIEW

**Comment by josephschorr** [comment]
Before I add tests: Currently, the registered methods are called with a set of generic args and kwargs maps, and the method returns a generic values map. Is this the approach we'd prefer or can we ensure type safety in a better fashion? Should the method being registered also have ability to return an error?

**Comment by jcelliott** [comment]
I think the generic arguments is good for now. We can add some reflection utilities on top of it later, but it's not necessary and will add some overhead. The YIELD and RESULT messages can both return positional values (`Arguments|list` in the docs) and named values (`ArgumentsKw|dict`), see the [YIELD](https://github.com/tavendo/WAMP/blob/master/spec/basic.md#yield-1) section of the WAMP documentation. So the `MethodHandler` should probably return `([]interface{}, map[string]interface{})`.

For returning an error, see the [invocation ERROR](https://github.com/tavendo/WAMP/blob/master/spec/basic.md#invocation-error) section. An invocation message can receive either YIELD or ERROR as a response. Also, a CALL message can receive either a RESPONSE or an ERROR.

**Comment by josephschorr** [comment]
How should we return the ERROR? Should the method called return an `error` instance, in addition to the slice and map?

**Comment by jcelliott** [comment]
Good point, `MethodHandler` should probably be:

```
func(args []interface{}, kwargs map[string]interface{}) ([]interface{}, map[string]interface{}, error)
```

Seems kind of long, but I don't see a better way to do it. What do you think?

**Comment by josephschorr** [comment]
Yeah, my main concern is length. Maybe we have a `CallResult` struct and have those fields inside? We could even have a set of methods to create it for common use cases (error, single value result, list, map, etc). Thoughts?

**Comment by jcelliott** [comment]
That's not a bad idea. If it works without being too awkward to use, let's try it.

**Comment by josephschorr** [comment]
Done as suggested and I added basic client tests for HELLO, CALL and REGISTER. Please let me know if the style is correct.

**Comment by jcelliott** [comment]
Thanks. This looks good after skimming through it. Let me look at it a bit more and I'll merge it later today.

**Pull request merged**
