### PR TITLE
Added the ability to register a connection callback.

### PR DESCRIPTION
**Pull request by bcurren**
I needed to add custom logic when a new connection is established or torn down. I added a callback mechanism that users of turnpike may use to perform any custom connection logic.

### CODE REVIEW

**Comment by maxekman** [comment]
This, and a lot more, is already implemented for both client and server in the dev branch (although not passing the actual WebSocket conn, which seems unnecessary.) I'm planning to add pub/sub handlers on the server also (to enable CRA authentication in the end.)

**Comment by jcelliott** [comment]
@bcurren, thanks for the contribution. Did you specifically need the Websocket conn object, or will the current implementation in the dev branch work for you?

**Comment by bcurren** [comment]
I needed the IP address of the client which is why I needed the connection
object. Also, the dev branch only has a call for session open but not
session closed. I need both callbacks to so I can perform setup and cleanup
per client.

---

Ben Curren
http://github.com/bcurren
http://twitter.com/bcurren
http://thecurrens.com

**Comment by jcelliott** [comment]
I'm not sure why I never merged this. All new development is being done for the WAMPv2 implementation on the v2 branch, and I've added an issue for that to add a similar feature (#58).

**Pull request closed without merging**
